/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPrincipalRouteImport } from './routes/_authenticated/principal'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCadastroIdRouteImport } from './routes/_authenticated/cadastro.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrincipalRoute = AuthenticatedPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadastroIdRoute = AuthenticatedCadastroIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCadastroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/principal': typeof AuthenticatedPrincipalRoute
  '/cadastro/$id': typeof AuthenticatedCadastroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/principal': typeof AuthenticatedPrincipalRoute
  '/cadastro/$id': typeof AuthenticatedCadastroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/principal': typeof AuthenticatedPrincipalRoute
  '/_authenticated/cadastro/$id': typeof AuthenticatedCadastroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/historico'
    | '/principal'
    | '/cadastro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/historico'
    | '/principal'
    | '/cadastro/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/cadastro'
    | '/_authenticated/configuracoes'
    | '/_authenticated/historico'
    | '/_authenticated/principal'
    | '/_authenticated/cadastro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/principal': {
      id: '/_authenticated/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof AuthenticatedPrincipalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro/$id': {
      id: '/_authenticated/cadastro/$id'
      path: '/$id'
      fullPath: '/cadastro/$id'
      preLoaderRoute: typeof AuthenticatedCadastroIdRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
  }
}

interface AuthenticatedCadastroRouteChildren {
  AuthenticatedCadastroIdRoute: typeof AuthenticatedCadastroIdRoute
}

const AuthenticatedCadastroRouteChildren: AuthenticatedCadastroRouteChildren = {
  AuthenticatedCadastroIdRoute: AuthenticatedCadastroIdRoute,
}

const AuthenticatedCadastroRouteWithChildren =
  AuthenticatedCadastroRoute._addFileChildren(
    AuthenticatedCadastroRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPrincipalRoute: typeof AuthenticatedPrincipalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCadastroRoute: AuthenticatedCadastroRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPrincipalRoute: AuthenticatedPrincipalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
